
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
import java.sql.*;
public class TiketPesawat extends javax.swing.JFrame {
    int ekonomi,bisnis,harga,beli,total,bayar,kembalian;

    
    public Statement st;
    public ResultSet rs;
    Connection cn = koneksi.koneksidatabase.BukaKoneksi();
    public TiketPesawat() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        Jurusan = new javax.swing.JLabel();
        Jenis = new javax.swing.JLabel();
        Harga = new javax.swing.JLabel();
        CBjurusan = new javax.swing.JComboBox<>();
        Rbekonomi = new javax.swing.JRadioButton();
        Rbbisnis = new javax.swing.JRadioButton();
        txtharga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btninput = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        btncetak = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtkursi = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtbeli = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        txtbayar = new javax.swing.JTextField();
        txtkembalian = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Ttabel = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea = new javax.swing.JTextArea();
        btnsimpan = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Data Pesawat"));

        Jurusan.setText("Jurusan");

        Jenis.setText("Jenis");

        Harga.setText("Harga");

        CBjurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Jakarta", "Bali", "Bandung", "Surabaya", " " }));
        CBjurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBjurusanActionPerformed(evt);
            }
        });

        Rbekonomi.setText("Ekonomi");
        Rbekonomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbekonomiActionPerformed(evt);
            }
        });

        Rbbisnis.setText("Bisnis");
        Rbbisnis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbbisnisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jurusan)
                    .addComponent(Jenis)
                    .addComponent(Harga))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CBjurusan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Rbbisnis)
                            .addComponent(Rbekonomi))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtharga))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jurusan)
                    .addComponent(CBjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jenis)
                    .addComponent(Rbekonomi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Rbbisnis)
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Harga)
                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 65, 168, 163);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nomor Kursi");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(213, 68, 80, 14);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nama Penumpang");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(213, 106, 130, 14);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Jumlah Beli");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(213, 144, 90, 14);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total Bayar");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(213, 182, 80, 14);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Uang Bayar");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(213, 220, 90, 14);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Uang Kembali");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(213, 258, 100, 14);

        btninput.setBackground(new java.awt.Color(255, 204, 204));
        btninput.setText("Input Lagi");
        btninput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninputActionPerformed(evt);
            }
        });
        getContentPane().add(btninput);
        btninput.setBounds(210, 300, 110, 23);

        btnkeluar.setBackground(new java.awt.Color(255, 204, 204));
        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnkeluar);
        btnkeluar.setBounds(327, 300, 70, 23);

        btncetak.setBackground(new java.awt.Color(255, 204, 204));
        btncetak.setText("Cetak");
        btncetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakActionPerformed(evt);
            }
        });
        getContentPane().add(btncetak);
        btncetak.setBounds(400, 300, 70, 23);

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtkursi, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 136, 30));

        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });
        jPanel1.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 135, 30));

        txtbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbeliActionPerformed(evt);
            }
        });
        txtbeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbeliKeyReleased(evt);
            }
        });
        jPanel1.add(txtbeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 135, 30));
        jPanel1.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 135, 30));

        txtbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbayarActionPerformed(evt);
            }
        });
        txtbayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbayarKeyReleased(evt);
            }
        });
        jPanel1.add(txtbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 135, 30));
        jPanel1.add(txtkembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 135, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Penjualan Tiket Pesawat");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        Ttabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nomor Kursi", "Nama Penumpang", "Jumlah Beli", "Total Bayar", "Uang Bayar", "Uang Kembalian"
            }
        ));
        jScrollPane3.setViewportView(Ttabel);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 510, 100));

        txtarea.setColumns(20);
        txtarea.setRows(5);
        jScrollPane1.setViewportView(txtarea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 460, 110));

        btnsimpan.setBackground(new java.awt.Color(255, 204, 204));
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setText("Ubah");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 100, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 20, 540, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btninputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninputActionPerformed
        // TODO add your handling code here:
        buttonGroup1.clearSelection();
        txtharga.setText("");
        CBjurusan.setSelectedItem("Pilih Jurusan");
        txtkursi.setText("");
        txtnama.setText("");
        txttotal.setText("");
        txtbeli.setText("");
        txtbayar.setText("");
        txtkembalian.setText("");
    }//GEN-LAST:event_btninputActionPerformed

    private void CBjurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBjurusanActionPerformed
        //membuat kondisi untuk menentukan harga sesuai jurusan
        if(CBjurusan.getSelectedItem().equals("Pilih Jurusan")){
            buttonGroup1.clearSelection();
            txtharga.setText("");
        }
        else if(CBjurusan.getSelectedItem().equals("Jakarta")){
            ekonomi=815000;
            bisnis=6500000;
        }
        else if(CBjurusan.getSelectedItem().equals("Bali")){
            ekonomi=77000;
            bisnis=1200000;
        }
        else if(CBjurusan.getSelectedItem().equals("Bandung")){
            ekonomi=810000;
            bisnis=5300000;
        }
        else if(CBjurusan.getSelectedItem().equals("Surabaya")){
            ekonomi=705000;
            bisnis=11900000;
        }
    }//GEN-LAST:event_CBjurusanActionPerformed

    private void RbekonomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbekonomiActionPerformed
        // menampilkan harga setelah pilih jenis kelas
        if(Rbekonomi.isSelected()){
            txtharga.setText(String.valueOf(ekonomi));
        }
        
    }//GEN-LAST:event_RbekonomiActionPerformed

    private void RbbisnisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbbisnisActionPerformed
        // menampilkan harga setelah pilih jenis kelas
        if(Rbbisnis.isSelected()){
            txtharga.setText(String.valueOf(bisnis));
    }//GEN-LAST:event_RbbisnisActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void txtbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbeliActionPerformed
        //menginput jumlah tiket dan mengetahui total pembayaran
        beli=Integer.parseInt(txtbeli.getText());
        harga=Integer.parseInt(txtharga.getText());
        total=bayar*harga;
        txttotal.setText(String.valueOf(total));
    }//GEN-LAST:event_txtbeliActionPerformed

    private void txtbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbayarActionPerformed
        // TODO add your handling code here:
        bayar=Integer.parseInt(txtbayar.getText());
        kembalian=Integer.parseInt(txttotal.getText());
        total=bayar-kembalian;
        txttotal.setText(String.valueOf(total));
    }//GEN-LAST:event_txtbayarActionPerformed

    private void txtbeliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbeliKeyReleased
        // TODO add your handling code here:
        int a,b,c;
        a=Integer.valueOf(txtharga.getText());
        b=Integer.valueOf(txtbeli.getText());
        c=a*b;
        txttotal.setText(""+c);
    }//GEN-LAST:event_txtbeliKeyReleased

    private void txtbayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbayarKeyReleased
        // TODO add your handling code here:
          int a,b,c;
        a=Integer.valueOf(txtbayar.getText());
        b=Integer.valueOf(txttotal.getText());
        c=a-b;
        txtkembalian.setText(""+c);
    }//GEN-LAST:event_txtbayarKeyReleased

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        int answer=JOptionPane.showConfirmDialog(null,"Anda Yakin Keluar?","Keluar",JOptionPane.OK_OPTION);
        if(answer==JOptionPane.OK_OPTION);
            dispose();
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void btncetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakActionPerformed
        // TODO add your handling code here:
        btncetak.setText((String)CBjurusan.getSelectedItem());
        txtarea.setText(
                "Nomor Kursi    :"+txtkursi.getText()+"\n"+
                "Nama Penumpang    :"+txtnama.getText()+"\n"+
                "Jumlah Beli    :"+txtbeli.getText()+"\n"+
                "Total Bayar    :"+txttotal.getText()+"\n"+
                "Uang Bayar    :"+txtbayar.getText()+"\n"+        
                "Uang Kembali   :"+txtkembalian.getText()+"\n");       
        
    }//GEN-LAST:event_btncetakActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnsimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TiketPesawat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TiketPesawat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TiketPesawat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TiketPesawat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TiketPesawat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBjurusan;
    private javax.swing.JLabel Harga;
    private javax.swing.JLabel Jenis;
    private javax.swing.JLabel Jurusan;
    private javax.swing.JRadioButton Rbbisnis;
    private javax.swing.JRadioButton Rbekonomi;
    private javax.swing.JTable Ttabel;
    private javax.swing.JButton btncetak;
    private javax.swing.JButton btninput;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnsimpan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtarea;
    private javax.swing.JTextField txtbayar;
    private javax.swing.JTextField txtbeli;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtkembalian;
    private javax.swing.JTextField txtkursi;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
